# Generated by Django 5.2.12 on 2026-03-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editora',
            name='site',
            field=models.CharField(max_length=100, verbose_name='Site da editora'),
        ),
        migrations.AlterField(
            model_name='leitor',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Email do leitor'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='preco',
            field=models.IntegerField(verbose_name='Preço do livro'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='status',
            field=models.BooleanField(verbose_name='Status do livro'),
        ),
    ]
