# Generated by Django 5.2.12 on 2026-03-23 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_editora_site_alter_leitor_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genero',
            options={},
        ),
    ]
